### ISSUE TITLE
client 无法连接：JSONDecodeError

### ISSUE THREAD

**Issue by hongjin95** [filamoon/pyapollo#16]
>>> client = pyapollo.ApolloClient(app_id='py-rds', cluster='default', config_server_url='http://10.64.141.26:11118')
>>> client.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hjyang\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyapollo-0.0.1.dev1-py3.6.egg\pyapollo\apollo_client.py", line 63, in start
    self._long_poll()
  File "C:\Users\hjyang\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyapollo-0.0.1.dev1-py3.6.egg\pyapollo\apollo_client.py", line 135, in _long_poll
    data = r.json()
  File "C:\Users\hjyang\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\hjyang\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\hjyang\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\hjyang\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by zhangwei2016** [comment]
是因为不支持python3？

**Comment by AndrewOYLK** [comment]
How to fix it ？
